spring:
  application:
    # Nombre del servicio; se usará para el registro en Eureka y Config Server
    name: licensing-service

server:
  # Puerto en el que escucha el servicio
  port: 8080

# Configuración de Actuator: expone los endpoints de salud y métricas
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
