server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # El propio eureka-server no se registra en sí mismo
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Tiempo de espera reducido para desarrollo local
    wait-time-in-ms-when-sync-empty: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info
