server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${ORG_DB_NAME:sma_organization}
    username: ${ORG_DB_USER:sma_user}
    password: ${ORG_DB_PASSWORD:sma_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          # El JwtDecoder resuelve el discovery del realm al arrancar -> Keycloak debe estar healthy
          issuer-uri: http://keycloak:8080/realms/sma

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
